# Generated by Django 5.2 on 2025-04-13 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_mobile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Egyptian phone number (e.g., 01012345678)', regex='^01[0-2,5]{1}[0-9]{8}$')]),
        ),
    ]
