# Generated by Django 5.1.7 on 2025-04-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_default_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Health', 'Health'), ('Education', 'Education'), ('Art', 'Art'), ('Charity', 'Charity')], max_length=50),
        ),
    ]
