# Generated by Django 5.2 on 2025-04-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_payment_paymob_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymob_payment_key',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
