# Generated by Django 5.2 on 2025-04-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='waiting', max_length=10),
        ),
    ]
