# Generated by Django 5.2 on 2025-04-29 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
    ]
