# Generated by Django 5.2 on 2025-04-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_project_status_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
    ]
