# Generated by Django 5.2 on 2025-04-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymob_order_id',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymob_payment_key',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
