# Generated by Django 5.2 on 2025-04-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_payment_paymob_payment_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymob_payment_key',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
