# Generated by Django 5.2 on 2025-04-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
