# Generated by Django 5.2 on 2025-05-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_category_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymob_order_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymob_payment_key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
