# Generated by Django 5.2 on 2025-05-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_payment_paymob_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paymob_order_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymob_payment_key',
            new_name='payment_key',
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
